export let ADD_INGREDIENT = 'ADD_INGREDIENT';
export let REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export let SET_INGREDIENTS = 'SET_INGREDIENTS';

export let PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export let PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';

export let AUTH_SUCCESS = 'AUTH_SUCCESS';
export let AUTH_START = 'AUTH_START';
export let AUTH_FAIL = 'AUTH_FAIL';